---
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'Rakefile'
    - 'libraries/**/*'
    - 'resources/**/*'
    - 'pkg/**/*'

Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/LineLength:
  Max: 200
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/StringLiterals:
  Exclude:
    - '*.gemspec'
    - 'Gemfile'

# TODOs
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
